### ISSUE TITLE
Use the Erlang logger

### ISSUE THREAD

**Issue by lpil** [bnprtr/comet#4]
Hello! Thanks for making this library, I like the kv-pair logging.

Currently this library prints to stdout rather than using the logger, which has performance implications when under load, doesn't integrate with other packages in Erlang/Gleam/etc, and misses out on all the features the logger provides.

It would be great to use the logger instead! The log emitting functions can use the logger ones, and the formatting etc functions can use the logger formatter APIs.

Thanks,
Louis

**Comment by bnprtr** [comment]
Sounds like a good suggestion to me. I'll work on drafting up some translation modules for javascript and erlang to keep the interfaces compatible.

**Comment by bnprtr** [comment]
With v0.2.x the package will use the erlang logger when using the erlang backend.
